name: bloc_learn
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0-110.0.dev

dependencies:
  flutter:
    sdk: flutter
  # 检测网络状态
  connectivity_plus: ^7.0.0
  # 图标库
  cupertino_icons: ^1.0.8
  # 状态管理
  flutter_bloc: ^9.1.1
  # 官方“注解工具包”
  meta: ^1.16.0
  # 本地持久化存储
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
